name: pysme
channels:
  - defaults
  - astropy
  - anaconda
  - conda-forge
dependencies:
  - python>=3.6
  - numpy=1.23.4
  - astropy=5.1.1
  - pandas=1.5.1
  - requests=2.28.1
  - scipy=1.9.3
  - libgfortran5
  - gcc
  - pip
  - pip:
    - tqdm==4.64.1
    - colorlog==6.7.0
    - emcee==3.1.3
    - pybtex==0.24.0
    - flex-format==0.2.18
    - plotly==5.11.0
    - matplotlib==3.6.1
